language: php

matrix:
  fast_finish: true

  include:
    - os: linux
      php: '7.2'
      env: PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"

    - os: linux
      php: '7.3'

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - if [[ $DISABLE_XDEBUG == "true" ]]; then phpenv config-rm xdebug.ini; fi

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction --ignore-platform-reqs

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS

after_success:
  - |
    if [[ $PHPUNIT_FLAGS != "" ]]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
      php php-coveralls.phar --verbose;
    fi
